version: '3'
services:
  portifolio_db:
    image: postgres:14.5-alpine
    container_name: portifolio_db
    restart: always
    environment: 
      - POSTGRES_PASSWORD=@Root123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=portifolio_database
    ports:
      - 5000:5432
    